### PR TITLE
APM-130 Remove SF20 Lidar legacy driver

### PR DESCRIPTION
**Pull request by rabad-matternet**
- removed legacy driver and all calls to it

### CODE REVIEW

**Review by viet-nguyen-matternet — COMMENTED** [review]
Do these changes mean we are successfully able to use the native sf20 driver during all boot sequences?

Additionally will we also remove:
AP_RangeFinder_LightWareI2C::legacy_get_reading
AP_RangeFinder_LightWareI2C::legacy_timer

**Review by adriennet823 — APPROVED** [review]

**Comment by rabad-matternet** [comment]
> Do these changes mean we are successfully able to use the native sf20 driver during all boot sequences?

All my attempts showed the native driver always loaded.
 
> Additionally will we also remove: AP_RangeFinder_LightWareI2C::legacy_get_reading 
> AP_RangeFinder_LightWareI2C::legacy_timer

Good catch!  Done!

**Review by zalice — APPROVED** [review]

**Comment by dat-tran-matternet** [comment]
Should you also remove the declarations in the header file (AP_RangeFinder_LightWareI2C.h) ?

**Comment by rabad-matternet** [comment]
> Should you also remove the declarations in the header file (AP_RangeFinder_LightWareI2C.h) ?

oh geez, how forgetful of me!!!
Done.

**Review by AydenChubbic — APPROVED** [review]

**Review by bhiln — APPROVED** [review]
Your PR comment mentions that you also removed all calls to these functions, but I only see that the functions were removed. Is that intensional?

**Review by dat-tran-matternet — APPROVED** [review]

**Comment by dat-tran-matternet** [comment]
Rebased to mttr-rebase-4.0

**Review by viet-nguyen-matternet — APPROVED** [review]

**Pull request merged**
