### PR TITLE
Added terrain generation script

### PR DESCRIPTION
**Pull request by tridge**
This allows for generation of terrain data which allows the GCS terrain protocol to be avoided

### CODE REVIEW

**Review by Aksellence — APPROVED** [review]
I can't see any noticeable issues. But would want to understand what exactly is the create_terrain script doing, and is going to work for our purposes.
Looks good.

**Comment by tridge** [comment]
> But would want to understand what exactly is the create_terrain script doing, and is going to work for our purposes.

what do you need to know beyond what you can get from the help and reading the script?

**Comment by zalice** [comment]
@AkshayMatternet does this make more sense after our discussion or do you have open questions?

**Comment by Aksellence** [comment]
> @AkshayMatternet does this make more sense after our discussion or do you have open questions?

Yeah, all the questions I had were answered during the discussion. Thanks!

**Review by Aksellence — APPROVED** [review]

**Review by zalice — APPROVED** [review]

**Review by adriennet823 — APPROVED** [review]
Awesome! Ran this myself and it worked great.

**Pull request merged**
