### PR TITLE
Copter: auto-reset baro cal when disarmed (for 4.0 branch)

### PR DESCRIPTION
**Pull request by tridge**
resets at 1Hz, as discussed with Alice

### CODE REVIEW

**Review by Aksellence — APPROVED** [review]
Looks good. Any way we could flight/ground test this @tridge?

**Comment by zalice** [comment]
> Looks good. Any way we could flight/ground test this @tridge?

@AkshayMatternet I recommend the same way that we tested the 3.6.7 patch for this. Please search confluence for my notes on that (I can link you to them).

**Comment by tridge** [comment]
rebased

**Comment by tridge** [comment]
rebased again

**Review by zalice — APPROVED** [review]

**Pull request merged**
